[supabase]
SUPABASE_URL = "https://alacgbvghdxvqpfzalrb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrd2xxbmJkZWhjYWFucGdzamV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzcxMTEsImV4cCI6MjA2ODUxMzExMX0.HCc6QlMnKcNLmO2uxVFARi6hV8hUjXGcmA71Xq2h9kM""
