[supabase]
url = "https://alacgbvghdxvqpfzalrb.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYWNnYnZnaGR4dnFwZnphbHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODU5MzYsImV4cCI6MjA2ODI2MTkzNn0.B7ZlY3GYMo-YGegr50kawkg_HPo-4J-VddDgGCX04eA"